name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test 2>&1 | tee test.log
      - run: npm run test:coverage 2>&1 | tee coverage.log
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.node-version }}
          path: |
            test.log
            coverage.log
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: Install ESLint
        run: npm install eslint --save-dev
      - name: Run ESLint
        run: npx eslint . 2>&1 | tee lint.log
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: lint-logs
          path: lint.log

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: Generate Documentation
        run: npm run docs 2>&1 | tee docs.log
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: docs-logs
          path: docs.log
          retention-days: 30
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/api
          branch: gh-pages