name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Use cache with the package-lock.json file
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - run: npm ci
      - run: npm test
      - run: npm run test:coverage
      
      # NPM publishing is now handled by the sync-to-public workflow
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Generate release file
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "# TaskBoardAI ${VERSION} Release Notes" > releases/${VERSION}.md
          echo "" >> releases/${VERSION}.md
          echo "## Changes in this release" >> releases/${VERSION}.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> releases/${VERSION}.md
          echo "" >> releases/${VERSION}.md
          echo "## Getting Started" >> releases/${VERSION}.md
          echo "See the [README.md](../README.md) for installation and usage instructions." >> releases/${VERSION}.md
      
      - name: Save artifacts locally
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            ./releases/${{ github.ref_name }}.md
            ./coverage/